/*
Copyright 2021 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "volcano.sh/volcano/pkg/apis/scheduling/v1beta1"
)

// FakeEvictEvents implements EvictEventInterface
type FakeEvictEvents struct {
	Fake *FakeSchedulingV1beta1
	ns   string
}

var evicteventsResource = schema.GroupVersionResource{Group: "scheduling.volcano.sh", Version: "v1beta1", Resource: "evictevents"}

var evicteventsKind = schema.GroupVersionKind{Group: "scheduling.volcano.sh", Version: "v1beta1", Kind: "EvictEvent"}

// Get takes name of the evictEvent, and returns the corresponding evictEvent object, and an error if there is any.
func (c *FakeEvictEvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EvictEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(evicteventsResource, c.ns, name), &v1beta1.EvictEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EvictEvent), err
}

// List takes label and field selectors, and returns the list of EvictEvents that match those selectors.
func (c *FakeEvictEvents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EvictEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(evicteventsResource, evicteventsKind, c.ns, opts), &v1beta1.EvictEventList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.EvictEventList{ListMeta: obj.(*v1beta1.EvictEventList).ListMeta}
	for _, item := range obj.(*v1beta1.EvictEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested evictEvents.
func (c *FakeEvictEvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(evicteventsResource, c.ns, opts))

}

// Create takes the representation of a evictEvent and creates it.  Returns the server's representation of the evictEvent, and an error, if there is any.
func (c *FakeEvictEvents) Create(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.CreateOptions) (result *v1beta1.EvictEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(evicteventsResource, c.ns, evictEvent), &v1beta1.EvictEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EvictEvent), err
}

// Update takes the representation of a evictEvent and updates it. Returns the server's representation of the evictEvent, and an error, if there is any.
func (c *FakeEvictEvents) Update(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.UpdateOptions) (result *v1beta1.EvictEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(evicteventsResource, c.ns, evictEvent), &v1beta1.EvictEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EvictEvent), err
}

// Delete takes name of the evictEvent and deletes it. Returns an error if one occurs.
func (c *FakeEvictEvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(evicteventsResource, c.ns, name), &v1beta1.EvictEvent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEvictEvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(evicteventsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.EvictEventList{})
	return err
}

// Patch applies the patch and returns the patched evictEvent.
func (c *FakeEvictEvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EvictEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(evicteventsResource, c.ns, name, pt, data, subresources...), &v1beta1.EvictEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EvictEvent), err
}
