/*
Copyright 2021 The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "volcano.sh/volcano/pkg/apis/scheduling/v1beta1"
	scheme "volcano.sh/volcano/pkg/client/clientset/versioned/scheme"
)

// EvictEventsGetter has a method to return a EvictEventInterface.
// A group's client should implement this interface.
type EvictEventsGetter interface {
	EvictEvents(namespace string) EvictEventInterface
}

// EvictEventInterface has methods to work with EvictEvent resources.
type EvictEventInterface interface {
	Create(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.CreateOptions) (*v1beta1.EvictEvent, error)
	Update(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.UpdateOptions) (*v1beta1.EvictEvent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.EvictEvent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.EvictEventList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EvictEvent, err error)
	EvictEventExpansion
}

// evictEvents implements EvictEventInterface
type evictEvents struct {
	client rest.Interface
	ns     string
}

// newEvictEvents returns a EvictEvents
func newEvictEvents(c *SchedulingV1beta1Client, namespace string) *evictEvents {
	return &evictEvents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the evictEvent, and returns the corresponding evictEvent object, and an error if there is any.
func (c *evictEvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EvictEvent, err error) {
	result = &v1beta1.EvictEvent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("evictevents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EvictEvents that match those selectors.
func (c *evictEvents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EvictEventList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.EvictEventList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("evictevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested evictEvents.
func (c *evictEvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("evictevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a evictEvent and creates it.  Returns the server's representation of the evictEvent, and an error, if there is any.
func (c *evictEvents) Create(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.CreateOptions) (result *v1beta1.EvictEvent, err error) {
	result = &v1beta1.EvictEvent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("evictevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(evictEvent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a evictEvent and updates it. Returns the server's representation of the evictEvent, and an error, if there is any.
func (c *evictEvents) Update(ctx context.Context, evictEvent *v1beta1.EvictEvent, opts v1.UpdateOptions) (result *v1beta1.EvictEvent, err error) {
	result = &v1beta1.EvictEvent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("evictevents").
		Name(evictEvent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(evictEvent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the evictEvent and deletes it. Returns an error if one occurs.
func (c *evictEvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("evictevents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *evictEvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("evictevents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched evictEvent.
func (c *evictEvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EvictEvent, err error) {
	result = &v1beta1.EvictEvent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("evictevents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
